env:
    NAME: cloudfresh-test-task
    REGION: europe-central2
    IMAGE: $gcr.io/${secrets.GCP_PROJECT_ID}/${NAME}:${COMMIT_SHA}

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${IMAGE}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${IMAGE}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - '${NAME}'
    - '--image'
    - '${IMAGE}'
    - '--region'
    - '${REGION}'

images:
  - $IMAGE
