substitutions:
  _NAME: cloudfresh-test-task
  _REGION: us-central1
  _IMAGE: gcr.io/${PROJECT_ID}/${_NAME}:${SHORT_SHA}

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - '${_NAME}'
    - '--image'
    - '${_IMAGE}'
    - '--region'
    - '${_REGION}'

images:
  - '${_IMAGE}'

options:
  logging: CLOUD_LOGGING_ONLY
