name: CICD

on:
  push:
    branches: 
      - master

env:
  REGION: europe-central2

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      
      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
        
      - name: Run Tests
        run: |
          source venv/bin/activate
          pytest
          
  build:
    runs-on: ubuntu-latest
  
    needs: test
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
  
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1  # Окремий крок для аутентифікації
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
  
    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev
  
    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/myapp-prod:$GITHUB_SHA .
      
    - name: Push Docker image to Artifact Registry
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/myapp-prod:$GITHUB_SHA
  
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy myapp-prod \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/myapp-prod:$GITHUB_SHA \
          --platform managed \
          --region ${{ env.REGION }} \
          --allow-unauthenticated
